name: V3 Pro Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * 1-5"

jobs:
  scanner:
    runs-on: ubuntu-latest

    env:
      DHAN_CLIENT_ID: ${{ secrets.DHAN_CLIENT_ID }}
      DHAN_ACCESS_TOKEN: ${{ secrets.DHAN_ACCESS_TOKEN }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scanner
        run: python main.py
